### PR TITLE
feat: add `context` to Chunk

### PR DESCRIPTION
**Pull request by TheCommieAxolotl**
Adds a `Chunk.context` entry with the context of the Chunk

e.g.
```diff
diff --git a/rename.js b/rename.js
index aa39060..0e05564 100644
--- a/rename.js
+++ b/rename.js
@@ -4 +4,5 @@ function hello() {
   // hello world
+  console.log("hello world");
```

will result in a chunk with
```js
{
	// ...
	context: "function hello() {",
    // ...
}
```

### CODE REVIEW

**Comment by TheCommieAxolotl** [comment]
@yeonjuan Just in case you missed it.

**Comment by yeonjuan** [comment]
Hi @TheCommieAxolotl , Thanks for the PR. I have a question.
Why we should add the context to the result?

**Comment by TheCommieAxolotl** [comment]
Thanks @yeonjuan, I'm using your package under the hood in an upcoming project of mine and I would like to display the context of diff chunks to the user to help them better understand where their code is. I was thinking about just writing my own parser to run as well as yours but I saw you were using a regex and it would be easy for me to contribute.

**Comment by yeonjuan** [comment]
@TheCommieAxolotl I got it. I think it's a bug. The result should contain `"function hello() {"` as a UnchangedLine (rather than add `context`). I'll work on it!

**Comment by TheCommieAxolotl** [comment]
@yeonjuan So you would just add an `UnchangedLine` to the beginning of the chunk?

**Comment by yeonjuan** [comment]
@TheCommieAxolotl Yes Right, the result should contain all lines!

**Comment by TheCommieAxolotl** [comment]
@yeonjuan I think you may be misunderstanding. The "context" isn't always part of the chunk, sometimes it can refer to a line several hundreds of lines above the current chunk and is just shown for orientation.

**Comment by yeonjuan** [comment]
@TheCommieAxolotl 
> @yeonjuan I think you may be misunderstanding. The "context" isn't always part of the chunk, sometimes it can refer to a line several hundreds of lines above the current chunk and is just shown for orientation.

Yes right, But I don't think we need new node type. Isn't this just the unchanged line output from the git-diff command?

**Comment by TheCommieAxolotl** [comment]
No, it is a separate part of the diff output. If you don't want to add a new entry to the chunk I understand but I think adding it as an `UnchangedLine` is incorrect behavior.

**Comment by yeonjuan** [comment]
@TheCommieAxolotl Sorry for the late reply.
> No, it is a separate part of the diff output

Could you give an example?  The `@@ -4 +4,5 @@` indicates the lines of changes. So it's not a separated part. Did i misunderstand?

**Comment by yeonjuan** [comment]
@TheCommieAxolotl 
You're right. I was misunderstanding, the string following the "@@" is not just representing the Unchaned Line. I'll do some more testing and review, thanks.

**Review by yeonjuan — APPROVED** [review]
LGTM! Thanks for the PR!

**Pull request merged**
